# Generated by Django 4.2 on 2023-05-01 16:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
