# Generated by Django 4.2 on 2023-05-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_alter_notification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('TK', 'Танк'), ('HL', 'Хил'), ('CY', 'ДД'), ('SN', 'Торговец'), ('GR', 'Гилдмастер'), ('QR', 'Квестгивер'), ('BH', 'Кузнец'), ('TR', 'Кожевник'), ('PR', 'Зельевар'), ('SR', 'Мастер Заклинаний')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
