# Generated by Django 4.2 on 2023-05-03 06:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_notification_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
