# Generated by Django 4.2 on 2023-05-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_alter_notification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notify.notification'),
        ),
    ]
