# Generated by Django 4.2 on 2023-05-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_alter_response_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.notification'),
        ),
    ]
